### ISSUE TITLE
Font Request: Geist by Vercel

### ISSUE THREAD

**Issue by Dax911** [fontsource/font-files#48] opened 2023-11-05 09:35 UTC
### Font Name

Geist

### Link to font source

https://github.com/vercel/geist-font

### Link to font license

https://github.com/vercel/geist-font/blob/main/LICENSE.TXT

### Additional context

Both the Geist Sans and Geist Mono.

**Comment by jwr1** [comment] 2023-11-05 19:26
Duplicate of #46.

**Closed by jwr1** 2023-11-05 19:26 UTC
Labels: font request
